<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { RouterLink, useRoute } from 'vue-router'
import { ApiError, apiRequest } from '../api/client'
import PurchaseCompletionPanel from '../components/PurchaseCompletionPanel.vue'
import type { OperationStatus, Purchase, PurchasePayment } from '../api/types'

const id = String(useRoute().params.id); const purchase = ref<Purchase | null>(null); const error = ref('')
const money = (value: number) => new Intl.NumberFormat('vi-VN').format(value)
async function load() { try { purchase.value = await apiRequest<Purchase>(`/api/purchases/${id}`) } catch (reason) { error.value = reason instanceof Error ? reason.message : 'Không thể tải phiếu nhập.' } }
async function complete(operationId: string, payments: Array<Pick<PurchasePayment, 'amount' | 'method'>>) { return apiRequest<Purchase>(`/api/purchases/${id}/complete`, { method: 'POST', body: JSON.stringify({ operationId, payments }) }) }
async function checkOperation(operationId: string) { try { return await apiRequest<OperationStatus>(`/api/operations/${operationId}`) } catch (reason) { if (reason instanceof ApiError && reason.status === 404) return null; throw reason } }
async function loadPurchase(purchaseId: string) { return apiRequest<Purchase>(`/api/purchases/${purchaseId}`) }
function completed(result: Purchase) { purchase.value = result }
onMounted(load)
</script>

<template><section><RouterLink class="text-sm font-semibold text-emerald-800" to="/purchases">← Danh sách phiếu nhập</RouterLink><p v-if="error" class="error mt-4">{{ error }}</p><template v-if="purchase"><div class="mt-3 flex flex-wrap justify-between gap-4"><div><h1 class="text-3xl font-black">Phiếu nhập · {{ purchase.supplierName }}</h1><p class="mt-1 text-slate-500">{{ purchase.status === 'Completed' ? 'Đã hoàn tất' : 'Nháp' }}</p></div><RouterLink v-if="purchase.status === 'Draft'" class="btn-secondary" :to="`/purchases/${id}/edit`">Sửa nháp</RouterLink></div><div class="card mt-6 overflow-x-auto p-0"><table class="w-full min-w-[650px] text-left text-sm"><thead class="border-b bg-stone-50"><tr><th class="p-4">Sản phẩm</th><th>Số lượng</th><th>Giá nhập</th><th>Thành tiền</th></tr></thead><tbody><tr v-for="line in purchase.lines" :key="line.id" class="border-b last:border-0"><td class="p-4 font-semibold"><RouterLink class="text-emerald-800 hover:underline" :to="`/products/${line.productId}`">{{ line.productName }}</RouterLink></td><td>{{ line.quantity }} {{ line.productUnit }}</td><td>{{ money(line.unitPrice) }} ₫</td><td>{{ money(line.lineAmount) }} ₫</td></tr></tbody></table></div><div class="mt-5 grid gap-4 sm:grid-cols-3"><div class="card"><span class="text-sm text-slate-500">Tổng</span><p class="text-2xl font-black">{{ money(purchase.totalAmount) }} ₫</p></div><div class="card"><span class="text-sm text-slate-500">Đã trả</span><p class="text-2xl font-black">{{ money(purchase.paidAmount) }} ₫</p></div><div class="card"><span class="text-sm text-slate-500">Còn nợ</span><p class="text-2xl font-black">{{ money(purchase.outstandingAmount) }} ₫</p></div></div><PurchaseCompletionPanel v-if="purchase.status === 'Draft'" class="mt-6" :purchase="purchase" :complete-purchase="complete" :check-operation="checkOperation" :load-purchase="loadPurchase" @completed="completed" /><div v-else class="card mt-6"><h2 class="text-xl font-black">Thanh toán đã ghi nhận</h2><p v-if="purchase.payments.length === 0" class="mt-3 text-slate-500">Chưa trả · toàn bộ là công nợ nhà cung cấp.</p><div v-for="payment in purchase.payments" :key="payment.id" class="mt-3 flex justify-between border-t pt-3"><span>{{ payment.method === 'Cash' ? 'Tiền mặt' : 'Chuyển khoản' }}</span><strong>{{ money(payment.amount) }} ₫</strong></div></div></template></section></template>
